/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package prefijovisual;

import java.awt.Color;
import java.io.*;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import validacion.Validacion;

/**
 *
 * @author jc389
 */
public class JPrefijo extends javax.swing.JPanel {

    ArrayList<Pais> pa = new ArrayList<>();
    String lada;
    Validacion v = new Validacion();

    /**
     * Creates new form PanelPrefijo
     */
    public JPrefijo() {
        initComponents();
        iniciar();
    }

    public void iniciar() {
        lblVal.setVisible(false);
        leerArchivos();
    }

    public void setNumero(String n) {
        txtNumerotel.setText(n);
    }

    public String getCombo() {
        String b = "" + lblLada.getText();
        return b;
    }

    public String getPais() {
        return "" + cboPrefijos.getSelectedItem();
    }

    public String getLada() {
        return lblLada.getText();
    }

    public String getNumero() {
        return txtNumerotel.getText();
    }

    public boolean validar() {
        if (v.vnumero(txtNumerotel.getText()) == false) {
            lblVal.setVisible(true);
            return false;
        } else {
            lblVal.setVisible(false);
            return true;
        }
    }

    public void ColorCaja(Color n) {
        txtNumerotel.setBackground(n);
    }

    public void leerArchivos() {
        String ruta = "/archivos/Paises.txt";
        InputStream input = getClass().getResourceAsStream(ruta);
        String nombre;
       
        try (InputStreamReader isr = new InputStreamReader(input)) {
            BufferedReader bf = new BufferedReader(isr);
            String linea;
            while ((linea = bf.readLine()) != null) {
                String[] au = linea.split(",");
                nombre = au[0];
                lada = au[1];

                Pais ps = new Pais(nombre, lada);
                pa.add(ps);
                lblLada.setText(pa.get(0).getLada());
                cboPrefijos.addItem(nombre);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se encontro el archivo");
        }
    }
    
    public void validarB() {
    String aux = "" + cboPrefijos.getSelectedItem();
    int i = 0;
    for (Pais pi : pa) {
        String ext = pi.getLada();
        String nb = pi.getNombre();
        if (nb.equals(aux)) {
            String imagePath = "/imagenes/" + nb + ".png"; // Ruta relativa dentro del classpath
            URL imageUrl = getClass().getResource(imagePath); // Obtiene la URL del recurso

            if (imageUrl != null) {
                ImageIcon cand = new ImageIcon(imageUrl);
                lblIcono.setIcon(cand);
                lblLada.setText(ext);
            } else {
                System.out.println("No se encontró la imagen: " + imagePath);
            }
        } else {
            i++;
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        cboPrefijos = new javax.swing.JComboBox<>();
        lblLada = new javax.swing.JLabel();
        txtNumerotel = new javax.swing.JTextField();
        ingrese = new javax.swing.JLabel();
        lblVal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        cboPrefijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPrefijosActionPerformed(evt);
            }
        });

        lblLada.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        txtNumerotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerotelActionPerformed(evt);
            }
        });
        txtNumerotel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumerotelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerotelKeyTyped(evt);
            }
        });

        ingrese.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ingrese.setText("Ingrese su número de teléfono.");

        lblVal.setForeground(new java.awt.Color(255, 0, 0));
        lblVal.setText("El número debe ser de 10 dígitos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(ingrese, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPrefijos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtNumerotel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lblVal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ingrese, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPrefijos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumerotel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblVal))
        );
    }// </editor-fold>                        

    private void cboPrefijosActionPerformed(java.awt.event.ActionEvent evt) {                                            
        validarB();

        // TODO add your handling code here:
    }                                           

    private void txtNumerotelActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (v.vnumero(txtNumerotel.getText()) == false) {
            lblVal.setVisible(true);
        } else {
            lblVal.setVisible(false);
        }


    }                                            

    private void txtNumerotelKeyPressed(java.awt.event.KeyEvent evt) {                                        

// TODO add your handling code here:
    }                                       

    private void formKeyReleased(java.awt.event.KeyEvent evt) {                                 
// TODO add your handling code here:
    }                                

    private void txtNumerotelKeyTyped(java.awt.event.KeyEvent evt) {                                      
        char c = evt.getKeyChar();
        // Verifica si el carácter no es un número
        if (!Character.isDigit(c)) {
            // Si no es un número, consume el evento para prevenir la entrada
            evt.consume();
        }        // TODO add your handling code here:
    }                                     


    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cboPrefijos;
    private javax.swing.JLabel ingrese;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblLada;
    private javax.swing.JLabel lblVal;
    private javax.swing.JTextField txtNumerotel;
    // End of variables declaration                   
}
